# Site settings
title:       An Open Letter
email:       pocha.sharma@gmail.com
author:      Ashish (Pocha) Sharma
description: "making democracy works better. more power to free speech"
baseurl:     ""
url:         "http://anopenlettr.com"

# Google analytics
google_analytics: UA-59880537-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: anopenlettr

# Social icons
show_social_icons: true
github_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
